# This file was automatically generated by rails by issuing the following command:
# 'rails generate migration add_password_digest_to_users password_digest:string'
# The 'to_users' suffix made rails construct the file in template to add columns to
# the 'users' table
class AddPasswordDigestToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :password_digest, :string
  end
end
